controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# notre accueil
homepage:
    path:      /
    controller:   App\Controller\NotrePremierController::index
